-- MySQL Script generated by MySQL Workbench
-- Thu Jul 11 16:24:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema GigaStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GigaStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GigaStore` DEFAULT CHARACTER SET utf8mb4 ;
USE `GigaStore` ;

-- -----------------------------------------------------
-- Table `GigaStore`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GigaStore`.`administrador` (
  `idadministrador` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministrador`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `GigaStore`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GigaStore`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `GigaStore`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GigaStore`.`carrito` (
  `idcarrito` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` TINYINT(1) NOT NULL,
  `cliente_idcliente` INT(11) NOT NULL,
  PRIMARY KEY (`idcarrito`, `cliente_idcliente`),
  INDEX `fk_carrito_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `GigaStore`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `GigaStore`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GigaStore`.`factura` (
  `idfactura` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `total` INT(10) NOT NULL,
  `estado` INT(11) NOT NULL DEFAULT 0,
  `cliente_idcliente` INT(11) NOT NULL,
  PRIMARY KEY (`idfactura`, `cliente_idcliente`),
  INDEX `fk_factura_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `GigaStore`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `GigaStore`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GigaStore`.`marca` (
  `idmarca` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `GigaStore`.`tipoproducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GigaStore`.`tipoproducto` (
  `idtipoproducto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoproducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `GigaStore`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GigaStore`.`producto` (
  `idproducto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `precio` INT(10) NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(100) NULL DEFAULT NULL,
  `marca_idmarca` INT(11) NOT NULL,
  `tipoproducto_idtipoproducto` INT(11) NOT NULL,
  PRIMARY KEY (`idproducto`, `marca_idmarca`, `tipoproducto_idtipoproducto`),
  INDEX `fk_producto_marca_idx` (`marca_idmarca` ASC) VISIBLE,
  INDEX `fk_producto_tipoproducto1_idx` (`tipoproducto_idtipoproducto` ASC) VISIBLE,
  CONSTRAINT `fk_producto_marca`
    FOREIGN KEY (`marca_idmarca`)
    REFERENCES `GigaStore`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_tipoproducto1`
    FOREIGN KEY (`tipoproducto_idtipoproducto`)
    REFERENCES `GigaStore`.`tipoproducto` (`idtipoproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `GigaStore`.`pcarrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GigaStore`.`pcarrito` (
  `carrito_idcarrito` INT(11) NOT NULL,
  `producto_idproducto` INT(11) NOT NULL,
  `cantidad` INT(1) NOT NULL,
  PRIMARY KEY (`carrito_idcarrito`, `producto_idproducto`),
  INDEX `fk_pcarrito_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_pcarrito_carrito1`
    FOREIGN KEY (`carrito_idcarrito`)
    REFERENCES `GigaStore`.`carrito` (`idcarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pcarrito_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `GigaStore`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `GigaStore`.`pfactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GigaStore`.`pfactura` (
  `factura_idfactura` INT(11) NOT NULL,
  `producto_idproducto` INT(11) NOT NULL,
  `unidades` INT(1) NOT NULL,
  `subtotal` INT(10) NOT NULL,
  PRIMARY KEY (`factura_idfactura`, `producto_idproducto`),
  INDEX `fk_facturaproducto_factura1_idx` (`factura_idfactura` ASC) VISIBLE,
  INDEX `fk_facturaproducto_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_facturaproducto_factura1`
    FOREIGN KEY (`factura_idfactura`)
    REFERENCES `GigaStore`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturaproducto_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `GigaStore`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
